<?php

/**
 * @file
 * Allows administrators to specify access control for taxonomy categories.
 */

/**
 * Maximum number of nodes for which to update node access within the module.
 *
 * If the number of affected nodes is greater, then node_access_needs_rebuild()
 * will be set instead.
 */
const TAXONOMY_ACCESS_MAX_UPDATE = 500;

/**
 * Base path for module administration pages.
 */
const TAXONOMY_ACCESS_CONFIG = 'admin/config/people/taxonomy_access';

/**
 * Global default.
 */
const TAXONOMY_ACCESS_GLOBAL_DEFAULT = 0;

/**
 * Vocabulary default.
 */
const TAXONOMY_ACCESS_VOCABULARY_DEFAULT = 0;

/**
 * 'Allow' grant value for nodes.
 */
const TAXONOMY_ACCESS_NODE_ALLOW = 1;

/**
 * 'Ignore' grant value for nodes.
 */
const TAXONOMY_ACCESS_NODE_IGNORE = 0;

/**
 * 'Deny' grant value for nodes.
 */
const TAXONOMY_ACCESS_NODE_DENY = 2;

/**
 * 'Allow' grant value for terms.
 */
const TAXONOMY_ACCESS_TERM_ALLOW = 1;

/**
 * 'Deny' grant value for terms.
 */
const TAXONOMY_ACCESS_TERM_DENY = 0;
